<?php
/**
 * Copyright © Risecommerce (support@risecommerce.com). All rights reserved.
 *
 */

/**
 * @var \Risecommerce\HtmlSitemap\Block\Cms\Page $block
 */
?>
<div class="sitemap-item-type sitemap-item-section">
    <br>
    <?php foreach ($block->getCmsPagesList() as $page): ?>
        <a href="<?= $block->escapeUrl($block->getBaseUrl() . $page->getIdentifier()) ?>" title="<?= $block->escapeHtml($page['title']) ?>">
            <?= $block->escapeHtml($page['title']) ?>
        </a>
    <?php endforeach; ?>
    <?php if ($pages = $block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $pages ?></div>
    <?php endif ?>
</div>
